name: pms

on:
  push:
    branches: [main]
#  pull_request:
#    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: |
          cd client-pms
          sudo npm i
          npm run build 
          sudo cp -r build ../
          cd ..
          sudo npm i
          npm run build
          sudo pm2 stop pm2.config.js
          sudo pm2 start pm2.config.js
          


